# Generated by Django 4.2.4 on 2023-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="slug",
            field=models.SlugField(default="test", unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/thumbnails/"
            ),
        ),
    ]
