# Generated by Django 4.2.4 on 2023-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_video_order_video_slug_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
