# Generated by Django 4.2.4 on 2023-09-01 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_alter_video_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
