# Generated by Django 4.2.4 on 2023-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Video Order"),
        ),
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Url Slug"),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="videos/thumbnails/",
                verbose_name="Video Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Video Title"),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_video_id",
            field=models.CharField(max_length=255, verbose_name="YouTube Video ID"),
        ),
    ]
