# Generated by Django 4.2.4 on 2023-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="members/images/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="members/videos/"),
        ),
    ]
