# Generated by Django 4.2.4 on 2023-09-20 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_banner_alter_article_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
