# Generated by Django 4.2.4 on 2023-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_profile_homepage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
