# Generated by Django 4.2.4 on 2023-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_profile_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
