# Generated by Django 4.2.4 on 2023-08-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
