# Generated by Django 4.2.4 on 2023-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_profile_cta_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="background_video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
