# Generated by Django 4.2.4 on 2023-08-30 14:45

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_profile_background_image_profile_background_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[members.models.validate_file_size],
            ),
        ),
    ]
