# Generated by Django 4.2.4 on 2023-08-30 14:57

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_alter_profile_background_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=members.models.user_directory_path_image,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=members.models.user_directory_path_video,
                validators=[members.models.validate_file_size],
            ),
        ),
    ]
