# Generated by Django 4.2.4 on 2023-08-30 15:12

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_profile_background_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuiltInVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video_file",
                    models.FileField(
                        upload_to="built_in_videos/",
                        validators=[members.models.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user_videos/",
                validators=[members.models.validate_file_size],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="built_in_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.builtinvideo",
            ),
        ),
    ]
