# Generated by Django 4.2.4 on 2023-09-04 21:36

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_remove_profile_homepage_image_profile_about_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_page_lifestyle_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=members.models.user_directory_path_image,
            ),
        ),
    ]
