# Generated by Django 4.2.4 on 2023-09-04 21:42

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_profile_home_page_lifestyle_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cta_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=members.models.user_directory_path_image,
            ),
        ),
    ]
