# Generated by Django 4.2.4 on 2023-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('interior_sqft', models.PositiveIntegerField()),
                ('lot_size', models.PositiveIntegerField()),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
