# Generated by Django 4.2.4 on 2023-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_remove_property_images_propertyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
