# Generated by Django 4.2.4 on 2023-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_property_bathrooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="property",
        ),
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.ManyToManyField(blank=True, to="properties.propertyimage"),
        ),
    ]
