# Generated by Django 4.2.4 on 2023-08-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_remove_propertyimage_property_property_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="images",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_images",
                to="properties.property",
            ),
        ),
    ]
