# Generated by Django 4.2.4 on 2023-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_alter_propertyimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="status",
        ),
        migrations.AddField(
            model_name="property",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
