# Generated by Django 4.2.4 on 2023-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_remove_property_status_property_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
