# Generated by Django 4.2.4 on 2023-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_property_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="priority",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
