# Generated by Django 4.2.4 on 2023-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0011_property_built_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuiltInProperty",
            fields=[],
            options={
                "verbose_name": "Built-In Property",
                "verbose_name_plural": "Built-In Properties",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("properties.property",),
        ),
        migrations.CreateModel(
            name="PropertyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_properties",
                        to="properties.property",
                    ),
                ),
                (
                    "related_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="properties",
            field=models.ManyToManyField(
                related_name="related_properties",
                through="properties.PropertyOrder",
                to="properties.property",
            ),
        ),
    ]
