# Generated by Django 4.2.4 on 2023-08-30 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0013_featuredlisting_featuredlistingorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredlisting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
