# Generated by Django 4.2.4 on 2023-08-30 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0014_featuredlisting_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredlistingorder",
            name="featured_listing",
        ),
        migrations.RemoveField(
            model_name="featuredlistingorder",
            name="property",
        ),
        migrations.DeleteModel(
            name="FeaturedListing",
        ),
        migrations.DeleteModel(
            name="FeaturedListingOrder",
        ),
    ]
