# Generated by Django 4.2.4 on 2023-09-04 23:58

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0017_alter_property_youtube_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                upload_to=properties.models.property_image_directory_path
            ),
        ),
    ]
