# Generated by Django 4.2.4 on 2023-09-12 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0018_alter_propertyimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="user",
        ),
        migrations.AddField(
            model_name="property",
            name="users",
            field=models.ManyToManyField(
                related_name="properties", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
