# Generated by Django 4.2.4 on 2023-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0019_remove_property_user_property_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(verbose_name="Property Description"),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Add to Home Page?"),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Property Brand"),
        ),
        migrations.AlterField(
            model_name="property",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Property Order"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Url Slug"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="tag",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Property Tag"
            ),
        ),
    ]
